version: '3'
services:
#mssql docker
  getfit-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - getfitnet

  getfit-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:local=Server=getfit-sql,1433;Database=140070;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 58065:80
    networks:
      - getfitnet
    links:
      - getfit-sql
    depends_on:
      - getfit-sql

networks:
  getfitnet:
    driver: bridge       